version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
    directory: "/"
    schedule:
      interval: "weekly"
