// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cheerio from "cheerio";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function findCabinetName(html) {
  var _cheerio = Cheerio.load(html);
  return _cheerio("h1").text();
}

function findRelevantTable(html, nameOptions) {
  var _cheerio = Cheerio.load(html);
  var maybeResult = Belt_Array.getBy(Belt_Array.map(nameOptions, (function (option) {
              var table = _cheerio("h2:contains(\"" + option + "\")");
              if (table.length > 0) {
                console.log("found table '" + option + "'");
              }
              return table;
            })), (function (table) {
          return table.length > 0;
        }));
  if (maybeResult !== undefined) {
    return Caml_option.valFromOption(maybeResult).nextAll("table").first().html();
  }
  throw new Error("Couldn't find relevant table with any of the names " + nameOptions.toString());
}

export {
  findCabinetName ,
  findRelevantTable ,
}
/* cheerio Not a pure module */
