// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function sameRow(cellA, cellB) {
  if (cellB.rowStart <= cellA.rowStart && cellA.rowStart <= cellB.rowEnd) {
    return true;
  } else if (cellB.rowStart <= cellA.rowEnd) {
    return cellA.rowEnd <= cellB.rowEnd;
  } else {
    return false;
  }
}

function createPolitician(amt, politicianName, party, imageUrl) {
  let message = "Cannot create politician object for name " + Core__Option.getExn(JSON.stringify(politicianName), undefined);
  return {
    amt: amt.linesOfText.join(", "),
    name: Core__Option.getExn(politicianName.linesOfText[politicianName.linesOfText.length - 1 | 0], message),
    imageUrl: Core__Option.getExn(imageUrl.imageUrl, message),
    party: Core__Option.getExn(party.linesOfText[0], message)
  };
}

export {
  sameRow,
  createPolitician,
}
/* No side effect */
