// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cheerio from "cheerio";

function _initializeCheerio(html) {
  if (html.indexOf("<html>") !== -1) {
    return Cheerio.load(html, null, true);
  } else {
    return Cheerio.load(html, null, false);
  }
}

export {
  _initializeCheerio ,
}
/* cheerio Not a pure module */
