// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Cheerio from "cheerio";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function load(html, maybeOptions, isDocument) {
  return Cheerio.load(html, maybeOptions, isDocument);
}

function cheerioToElementArray(cheerio) {
  return cheerio.toArray();
}

function getParent(element) {
  return element.parent;
}

function getChildren(element) {
  return element.children;
}

function getType(element) {
  return element.type;
}

function getData(element) {
  if (element.type !== "text") {
    Js_exn.raiseError("Trying to get 'data' from non-text element");
  }
  return element.data;
}

function getName(element) {
  return element.name;
}

var CheerioFacade = {
  load: load,
  cheerioToElementArray: cheerioToElementArray,
  getParent: getParent,
  getChildren: getChildren,
  getType: getType,
  getData: getData,
  getName: getName
};

function _initializeCheerio(html) {
  if (html.indexOf("<html>") !== -1) {
    return load(html, null, true);
  } else {
    return load(html, null, false);
  }
}

function _sanityCheckHeaders(cheerioWithHeaders) {
  var headerElements = cheerioWithHeaders.toArray();
  var parent = Belt_Option.getExn(Belt_Array.getExn(headerElements, 0).parent);
  var maybeInvalidHeader = Belt_Array.getBy(headerElements, (function (header) {
          return Belt_Option.getExn(header.parent) !== parent;
        }));
  if (maybeInvalidHeader === undefined) {
    return ;
  }
  var invalidHeader = Caml_option.valFromOption(maybeInvalidHeader);
  var thText = Belt_Array.map(invalidHeader.children, getData).toString();
  var expected = parent.name;
  var actual = Belt_Option.getExn(invalidHeader.parent).name;
  throw new Error("Multiple headline rows--that's bad. <th>" + thText + "</th>. Expected parent element " + expected + ", but was " + actual);
}

export {
  CheerioFacade ,
  _initializeCheerio ,
  _sanityCheckHeaders ,
}
/* cheerio Not a pure module */
