name: "Check For Wiki Updates"

# Daily at Midnight and with every push (to see result of new changes)
on:
  schedule:
    - cron: "00 00 * * *"
  push:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: yarn --frozen-lockfile
      - run: yarn start
      # ACTUAL CHECK
      - name: Compare output with checked-in version
        run: |
          git status --porcelain
          STATUS=$(git status --porcelain)
          if [[ ! $STATUS ]]; then echo "empty"; else git --no-pager diff && exit 1; fi
