name: 'Check For Wiki Updates'

on:
    schedule:
        - cron: '00 00 * * *' # daily at Midnight
    push: # All push events

jobs:
    schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn start
            # ACTUAL CHECK
            - name: Check if there are changes
              run: "git status --porcelain"
